config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  get '/:locale' => 'pages#home'
  root to: redirect("/#{I18n.default_locale}"), as: :redirected_root

  scope "/:locale" do
    root to: 'pages#home'
    resources :projects
    resources :users
    resources :wedding_party_members
    get '/login', to: 'sessions#login'
    post '/login', to: 'sessions#create'
    post '/logout', to: 'sessions#destroy'
    get '/logout', to: 'sessions#destroy'
  end

end

app/models/wedding_party_member.rb
class WeddingPartyMember < ApplicationRecord
  belongs_to :project
  enum role: { undefined: 0, bridesmaid: 1, groomsman: 2, ringbearer: 3, flowergirl: 4, fatherbride: 5, motherbride: 6, fathergroom: 7, mothergroom: 8, bestman: 9, maidofhonor: 10, matronofhonor: 11, lector: 12, musician: 13, altarserver: 14, concelebrant: 15, groomswoman: 16, bridesman: 17, chorist: 18, soloist: 19 }, _prefix: true
  enum relationship: { undefined: 0, grandfather: 1, grandmother: 2, brother: 3, sister: 4, aunt: 5, uncle: 6, cousin: 7, nephew: 8, niece: 9, relative: 10, friend: 11, stepfather: 12, stepmother: 13, stepbrother: 14, stepsister: 15, greatgrandfather: 16, greatgrandmother: 17, greatuncle: 18, greataunt: 19 }, _prefix: true
end

app/controllers/wedding_party_members_controller.rb
class WeddingPartyMembersController < ApplicationController
  before_action :set_wedding_party_member, only: %i[ show edit update destroy ]

  # GET /wedding_party_members or /wedding_party_members.json
  def index
    @wedding_party_members = WeddingPartyMember.all
  end

  # GET /wedding_party_members/1 or /wedding_party_members/1.json
  def show
  end

  # GET /wedding_party_members/new
  def new
    @wedding_party_member = WeddingPartyMember.new
  end

  # GET /wedding_party_members/1/edit
  def edit
  end

  # POST /wedding_party_members or /wedding_party_members.json
  def create
    @wedding_party_member = WeddingPartyMember.new(wedding_party_member_params)

    respond_to do |format|
      if @wedding_party_member.save
        format.html { redirect_to wedding_party_member_url(@wedding_party_member), notice: "Wedding party member was successfully created." }
        format.json { render :show, status: :created, location: @wedding_party_member }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @wedding_party_member.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /wedding_party_members/1 or /wedding_party_members/1.json
  def update
    respond_to do |format|
      if @wedding_party_member.update(wedding_party_member_params)
        format.html { redirect_to wedding_party_member_url(@wedding_party_member), notice: "Wedding party member was successfully updated." }
        format.json { render :show, status: :ok, location: @wedding_party_member }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @wedding_party_member.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /wedding_party_members/1 or /wedding_party_members/1.json
  def destroy
    @wedding_party_member.destroy

    respond_to do |format|
      format.html { redirect_to wedding_party_members_url, notice: "Wedding party member was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_wedding_party_member
      @wedding_party_member = WeddingPartyMember.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def wedding_party_member_params
      params.require(:wedding_party_member).permit(:namePrefix, :firstName, :lastName, :role, :relationship, :relationshipTo, :project_id)
    end
end

app/helpers/wedding_party_members_helper.rb
module WeddingPartyMembersHelper
end

app/views/wedding_party_members/_form.html.erb
<%= form_with(model: wedding_party_member, class: "contents") do |form| %>
  <% if wedding_party_member.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(wedding_party_member.errors.count, "error") %> prohibited this wedding_party_member from being saved:</h2>

      <ul>
        <% wedding_party_member.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :namePrefix %>
    <%= form.text_field :namePrefix, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :firstName %>
    <%= form.text_field :firstName, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :lastName %>
    <%= form.text_field :lastName, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :role %>
    <%= form.select :role, WeddingPartyMember.roles.keys.map{ |key, value| [ t("activerecord.attributes.wedding_party_member.role_#{key}"), key ] } %>
  </div>

  <div class="my-5">
    <%= form.label :relationship %>
    <%= form.select :relationship, WeddingPartyMember.relationships.keys.map{ |key, value| [ t("activerecord.attributes.wedding_party_member.relationship_#{key}"), key ] } %>
  </div>

  <div class="my-5">
    <%= form.label :relationshipTo %>
    <%= form.text_field :relationshipTo, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :project_id %>
    <%= form.text_field :project_id, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/wedding_party_members/_wedding_party_member.html.erb
<div id="<%= dom_id wedding_party_member %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Firstname:</strong>
    <%= wedding_party_member.namePrefix %>
  </p>
  <p class="my-5">
    <strong class="block font-medium mb-1">Firstname:</strong>
    <%= wedding_party_member.firstName %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Lastname:</strong>
    <%= wedding_party_member.lastName %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Role:</strong>
    <%= wedding_party_member.role %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Relationship:</strong>
    <%= wedding_party_member.relationship %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Relationshipto:</strong>
    <%= wedding_party_member.relationshipTo %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Project:</strong>
    <%= wedding_party_member.project_id %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this wedding party member", wedding_party_member, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to 'Edit this wedding party member', edit_wedding_party_member_path(wedding_party_member), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/wedding_party_members/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing wedding party member</h1>

  <%= render "form", wedding_party_member: @wedding_party_member %>

  <%= link_to "Show this wedding party member", @wedding_party_member, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to wedding party members", wedding_party_members_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/wedding_party_members/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Wedding party members</h1>
    <%= link_to 'New wedding party member', new_wedding_party_member_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="wedding_party_members" class="min-w-full">
    <%= render @wedding_party_members %>
  </div>
</div>

app/views/wedding_party_members/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New wedding party member</h1>

  <%= render "form", wedding_party_member: @wedding_party_member %>

  <%= link_to 'Back to wedding party members', wedding_party_members_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/wedding_party_members/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @wedding_party_member %>

    <%= link_to 'Edit this wedding_party_member', edit_wedding_party_member_path(@wedding_party_member), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this wedding_party_member', wedding_party_member_path(@wedding_party_member), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to wedding_party_members', wedding_party_members_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>